name: Run Selenium Script

on:
  push:
    branches:
      - main

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install selenium
          pip install pytest
          pip install junit-xml

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run Selenium script
        run: pytest --junitxml=report.xml